Revert "prevent long ssh connections via githook"
This reverts commit d7e0b08687cde894276c3db74518f13a0981c818.

diff --git a/ahtapotmys/roles/ansible/templates/gdys.sh.j2 b/ahtapotmys/roles/ansible/templates/gdys.sh.j2
--- a/ahtapotmys/roles/ansible/templates/gdys.sh.j2
+++ b/ahtapotmys/roles/ansible/templates/gdys.sh.j2
@@ -4,4 +4,13 @@
 
 #!/bin/bash
 
-sudo touch /var/run/firewall
+/usr/bin/ansible-playbook /etc/ansible/playbooks/updategdysrepo.yml
+
+EXIT=$?
+
+if [ "$EXIT" -eq 0 ]
+then
+        /usr/bin/ansible-playbook /etc/ansible/playbooks/firewall.yml
+else
+        logger -p local5.crit "Ansible GDYS Repo Update Failed !!"
+fi
diff --git a/ahtapotmys/roles/ansible/templates/mys.sh.j2 b/ahtapotmys/roles/ansible/templates/mys.sh.j2
--- a/ahtapotmys/roles/ansible/templates/mys.sh.j2
+++ b/ahtapotmys/roles/ansible/templates/mys.sh.j2
@@ -4,4 +4,13 @@
 
 #!/bin/bash
 
-sudo touch /var/run/state
+/usr/bin/ansible-playbook /etc/ansible/playbooks/updatemysrepo.yml
+
+EXIT=$?
+
+if [ "$EXIT" -eq 0 ]
+then
+        /usr/bin/ansible-playbook /etc/ansible/playbooks/state.yml
+else
+        logger -p local5.crit "Ansible MYS Repo Update Failed !!"
+fi
